### PR TITLE
Windows fixes and Timeshift buffer deletion

### LINKED ISSUE #114: Possible race condition on startup
On occasion Kodi will reboot on startup. Possibly related to the addon.

Look at mutexes to make sure they are all correctly in place.

### LINKED ISSUE #115: tsbuffer.ts never got deleted
my shield was just running out of space, then i found in pvr.vuplus folder a file called tsbuffer.ts with 6gb size. shouldnt this file be automaticly deleted if i close pvr or change the channel?
the last time, i used timeshift is some days ago.
how will this file be deleted automaticly?

### PR DESCRIPTION
**Pull request by phunkyfish**
v3.12.6
- Fixed: Possible race condition on startup, fixes #114
- Fixed: Windows build in Epg.cpp
- Fixed: tsbuffer.ts never got deleted, fixes #115

First appears to be a race condition on addon startup, I have to start the addon about 50 times to get it to happen. Welcome any feedback how I added the lock objects. I referenced several other addons to see how it was done there so I think  have everything covered. On the third the Epg.cpp fixed worked bu now's it's stuck on AutoTimer.cpp

### CODE REVIEW

**Comment by phunkyfish** [comment]
@Rechi I see there is jenkins now. I can't see what the issue is from the UI, it looks like a build error but I don't see how it's code related.

**Comment by phunkyfish** [comment]
Going to push this again. Missing a file from #114 fix and fix for #115

**Comment by phunkyfish** [comment]
Ok I've pushed again. Still on clue on why the build is failing on AutoTimer.cpp, it's like it can't see it's own header file.

**Comment by ksooo** [comment]
Show me the error message, please.

**Comment by Rechi** [comment]
@ksooo look into the jenkins pr status check.

**Comment by ksooo** [comment]
```
D:\jenkins\workspace\binary-addons\kodi-windows-x86_64-master\tools\depends\target\binary-addons\pvr.vuplus\src\enigma2\data\AutoTimer.cpp(82): error C2061: syntax error: identifier 'Channels'
```

 The type seems not to be found. Missing include? namespace problem?

File: src/enigma2/Epg.cpp [hunk 1]
```diff
@@ -10,6 +10,10 @@
 #include "util/XMLUtils.h"
 #include "p8-platform/util/StringUtils.h"
 
+#if defined(_WIN32)
+#include <Bits.h>
```
[the remark this answers is not in the document]
Comment (phunkyfish) [reply src/enigma2/Epg.cpp]: I simply reused the code from the old source file. I would far prefer to this in a platform independent way but have a knowledge gap in how to do so. I can try using a char type instead. That's what I would have used in the old days in C.

File: src/enigma2/TimeshiftBuffer.cpp [hunk 2]
```diff
@@ -39,6 +39,10 @@ TimeshiftBuffer::~TimeshiftBuffer(void)
   }
   if (m_filebufferReadHandle)
     XBMC->CloseFile(m_filebufferReadHandle);
+  
+  if (XBMC->FileExists(m_bufferPath.c_str(), false))
```
[the remark this answers is not in the document]
Comment (phunkyfish) [reply src/enigma2/TimeshiftBuffer.cpp]: Ok, makes sense.

**Comment by phunkyfish** [comment]
Don't I feel like an idiot. Spent hours blindly looking at the code and it's obvious now. Thanks @ksooo 

As the lock code is controversial I will remove it from this PR so we can get the build back working. I'll put it in a separate PR for discussion. What I need with it is some guidance on how to resolve the issue.

**Comment by ksooo** [comment]
> As the lock code is controversial I will remove it from this PR so we can get the build back working. I'll put it in a separate PR for discussion. What I need with it is some guidance on how to resolve the issue.

 Sounds like a good plan. Thanks.

**Comment by ksooo** [comment]
> Don't I feel like an idiot. Spent hours blindly looking at the code and it's obvious now

 I know that feeling... :-)

File: src/enigma2/Epg.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (ksooo) [reply src/enigma2/Epg.cpp]: If it was in the old code, it should be fine for now. Just wanted to prevent introduction of new bustards of this kind.

[the remark this answers is not in the document]
Comment (phunkyfish) [reply src/enigma2/Epg.cpp]: I just pushed the chaige using char instead of byte. Should I revert?

**Comment by phunkyfish** [comment]
Ok, should be good now.

I'm curious as to why the namespace issues were a problem in Windows but not on any other platform.

**Comment by phunkyfish** [comment]
@ksooo I don't appear to be able to resolve you previous review. Maybe as I had already pushed the branch.

File: src/enigma2/TimeshiftBuffer.cpp [hunk 3]
```diff
@@ -39,6 +39,16 @@ TimeshiftBuffer::~TimeshiftBuffer(void)
   }
   if (m_filebufferReadHandle)
     XBMC->CloseFile(m_filebufferReadHandle);
+  
+  try
+  {
+    XBMC->DeleteFile(m_bufferPath.c_str());
+  }
+  catch (...)
```
Comment (ksooo) [inline src/enigma2/TimeshiftBuffer.cpp]: Are you sure that `DeleteFile` actually throws an exception if something goes wrong? 

https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-addon-dev-kit/include/kodi/libXBMC_addon.h#L499

Method signature does no contain a throw clause. Error seems to be propagated using the `bool` return value only.

**Comment by phunkyfish** [comment]
@ksooo for the change in Epg.cpp any reason not to use char instead of byte?

**Comment by ksooo** [comment]
> for the change in Epg.cpp any reason not to use char instead of byte?

 No reason.

**Comment by phunkyfish** [comment]
Ok, I change the DeleteFile call to a condition instead. Also, I removed ifdef WIN32 from Enigma2.cpp as it's no longer required.

Hopefully, we are good now.

File: src/enigma2/TimeshiftBuffer.cpp [hunk 4]
```diff
@@ -39,6 +39,10 @@ TimeshiftBuffer::~TimeshiftBuffer(void)
   }
   if (m_filebufferReadHandle)
     XBMC->CloseFile(m_filebufferReadHandle);
+  
+  if (!XBMC->DeleteFile(m_bufferPath.c_str()))
```
Comment (Jalle19) [inline src/enigma2/TimeshiftBuffer.cpp]: This can be troublesome, I did this in pvr.vbox:  https://github.com/kodi-pvr/pvr.vbox/blob/master/src/timeshift/FilesystemBuffer.cpp (see the undef, can't link from mobile)

Comment (phunkyfish) [reply src/enigma2/TimeshiftBuffer.cpp]: Thanks, I’ll add the undef for Windows. @ksooo, looks like I’ll have to do something platform dependent now anyways unless you have a better suggestion?

Comment (ksooo) [reply src/enigma2/TimeshiftBuffer.cpp]: no better suggestion atm :-/

Comment (Rechi) [reply src/enigma2/TimeshiftBuffer.cpp]: As this currently compiles, you don't have to care about it.
It's needed in pvr.vbox as windows headers are pulled in somewhere.

**Comment by phunkyfish** [comment]
Ok, so I’ll revert again.

File: src/enigma2/TimeshiftBuffer.cpp (hunk 4 above)
Comment (phunkyfish) [reply src/enigma2/TimeshiftBuffer.cpp]: @Jalle19 so was the error you had at runtime or compile time?

**Comment by phunkyfish** [comment]
Ok, I'm remove the WIN32 undef. 

Should be finally, finally ready to go ;)

File: src/enigma2/TimeshiftBuffer.cpp (hunk 4 above)
Comment (Jalle19) [reply src/enigma2/TimeshiftBuffer.cpp]: I honestly can't remember

**Comment by phunkyfish** [comment]
No worries, sure we’ll suck it and see.
