### PR TITLE
Async connection

### LINKED ISSUE #154: Plugin fails to load if sat receiver is powered on after Kodi start
Hi there,

if I start my VUSolo 2 minutes before Kodi starts on my FireTVStick2, everything works fine.
Channel list is loaded (and also recordings, but I don't need recordings).

However, if my Kodi is already running and I start my VUSolo now, Kodi/Enigma2 wil never load channels.
I can see "PVR Manager is starting up, stuck at 0%".
I then have to restart KODI in order to see the channel list.

This has been a bug for several Kodi versions (I'm currently using Kodi 18 RC3).
Before Kodi RC3 the plugin was called VUSolo, but now it seems to be renamed to "Enigma2".
But I remember that a few versions back (maybe Kodi 14 or 15?) I was able to start my VUSolo after Kodi start, and channel list was loaded afterwards.

I hope this can be fixed soon,
best regards,

Heiko

### LINKED ISSUE #179: EPG update broken when Channel changes transponder or is renamed
I've updated to 3.16.2.2 today and wanted to check if #158  is fixed. But now, i can't get epg data:

```
00:01:48.300 T:3671061360  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - GetEPGForChannel Could not find <e2event> element
00:01:48.300 T:3671061360   ERROR: GetEPGForChannel: Add-on 'ET9200:10.2.11.24' returned an error: server error
00:01:48.300 T:3671061360   ERROR: Update: Failed to update table '<n/a>'
00:01:48.438 T:3671061360  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - GetEPGForChannel Could not find <e2event> element
00:01:48.438 T:3671061360   ERROR: GetEPGForChannel: Add-on 'ET9200:10.2.11.24' returned an error: server error
00:01:48.438 T:3671061360   ERROR: Update: Failed to update table '<n/a>'
00:01:48.572 T:3671061360  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - GetEPGForChannel Could not find <e2event> element
00:01:48.572 T:3671061360   ERROR: GetEPGForChannel: Add-on 'ET9200:10.2.11.24' returned an error: server error
00:01:48.573 T:3671061360   ERROR: Update: Failed to update table '<n/a>'
00:01:50.037 T:3671061360  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - GetEPGForChannel Could not find <e2event> element
00:01:50.037 T:3671061360   ERROR: GetEPGForChannel: Add-on 'ET9200:10.2.11.24' returned an error: server error
```

- Playback of recordings is working.
- LiveTV is also working

My enigma2 receiver is running on OWIF 1.3.5.

### LINKED ISSUE #184: Kodi does not exit (for several minutes) if Enigma2-receiver is not reachable
Hi,

I found another bug releated to:
https://github.com/kodi-pvr/pvr.vuplus/issues/154

If Enigma2-plugin is enabled and Enigma2-receiver is offline (e.g. in deep standby), I cannot exit Kodi.
Kodi seems to hang for a very long time, although time varies (from 30 seconds to over 15 minutes!).
Sometimes I have to kill Kodi through FireTVStick2 settings menu.

The problem is reproducable:
If I disable the Enigma2 plugin while Enigma2 is offlline, Kodi exits immediately.
If I enable Enigma2 plugin again (while Engima2 receiver is still in deep standby), Exit seems to hang again.

I hope you can fix this bug as well.

Greetings,
Heiko

### LINKED ISSUE #185: Instant Recordings that record part of a show are missing show info
The lookup on openwebif should use the actual start time instead of the altered start time so the info is collected successfully.

### LINKED ISSUE #186: Recordings are missing genre info
This is due to the fact that E2 devices do not store genre information. Could use the tags field on the timer to store this. This should work for both regular timers and auto timers

### PR DESCRIPTION
**Pull request by phunkyfish**
v3.19.0
- Added: Async Connection - Reconnect if Enigma2 device was or becomes unavailable, closes #154, closes #184
- Added: Notify when Channel/ChannelGroups changes are detected, closes #179
- Added: Support genres for Recordings and Timers, fixes #186
- Fixed: Instant recordings may be missing show info depending on last EPG update, fixes #185
- Added: Helper build script for MacOSX

### CODE REVIEW

File: src/enigma2/data/ChannelGroup.cpp [hunk 1]
```diff
@@ -8,6 +8,39 @@ using namespace enigma2;
 using namespace enigma2::data;
 using namespace enigma2::utilities;
 
+bool ChannelGroup::Like(const ChannelGroup &right) const
+{
+  bool isLike = true;
+  isLike = isLike && (m_serviceReference == right.m_serviceReference);
+  isLike = isLike && (m_groupName == right.m_groupName);
```
Comment (ksooo) [inline src/enigma2/data/ChannelGroup.cpp]: see my previous comments.

File: src/enigma2/data/ChannelGroup.cpp [hunk 2]
```diff
@@ -8,6 +8,39 @@ using namespace enigma2;
...
+{
+  bool isEqual = true;
+  isEqual = isEqual && (m_serviceReference == right.m_serviceReference);
+  isEqual = isEqual && (m_groupName == right.m_groupName);
+  isEqual = isEqual && (m_radio == right.m_radio);
+  isEqual = isEqual && (m_lastScannedGroup == right.m_lastScannedGroup);
+
+  for (int i = 0; i < m_channelList.size(); i++)
+  {
+    isEqual = isEqual && (*(m_channelList.at(i)) == *(right.m_channelList.at(i)));
```
Comment (ksooo) [inline src/enigma2/data/ChannelGroup.cpp]: see my previous comments

File: src/enigma2/data/ChannelGroup.cpp [hunk 3]
```diff
@@ -8,6 +8,39 @@ using namespace enigma2;
...
+
+bool ChannelGroup::operator==(const ChannelGroup &right) const
+{
+  bool isEqual = true;
+  isEqual = isEqual && (m_serviceReference == right.m_serviceReference);
+  isEqual = isEqual && (m_groupName == right.m_groupName);
+  isEqual = isEqual && (m_radio == right.m_radio);
+  isEqual = isEqual && (m_lastScannedGroup == right.m_lastScannedGroup);
+
+  for (int i = 0; i < m_channelList.size(); i++)
```
Comment (ksooo) [inline src/enigma2/data/ChannelGroup.cpp]: using a range-based loop here would be more "sexy", espacially as ugly `at(i)` calls are not needed, then.

File: src/Enigma2.cpp [hunk 4]
```diff
@@ -347,20 +392,28 @@ PVR_ERROR Enigma2::GetEPGForChannel(ADDON_HANDLE handle, const PVR_CHANNEL &chan
   if (m_epg.IsInitialEpgCompleted() && m_settings.GetEPGDelayPerChannelDelay() != 0)
     Sleep(m_settings.GetEPGDelayPerChannelDelay());
 
-  if (!m_channels.IsValid(channel.iUniqueId))
+  //Have a lock while getting the channel. Then we don't have to worry about a disconnection while retrieving the EPG data.
+  std::shared_ptr<Channel> myChannel = nullptr;
```
Comment (ksooo) [inline src/Enigma2.cpp]: No need to assign nullptr, will be done automatically by std::shared_ptr ctor (and this time I'm right, remember my brain fart with std::make_shared? :-)

File: src/enigma2/ConnectionManager.cpp [hunk 5]
```diff
@@ -0,0 +1,180 @@
...
+ *
+ */
+
+#include "ConnectionManager.h"
+
+// extern "C"
+// {
+// #include "libhts/htsmsg_binary.h"
+// #include "libhts/sha1.h"
+// }
```
Comment (ksooo) [inline src/enigma2/ConnectionManager.cpp]: Remove this. I see you got inspiration from pvr.hts (=> libhts)? ;-)

File: src/enigma2/ConnectionManager.cpp [hunk 6]
```diff
@@ -0,0 +1,180 @@
...
+using namespace enigma2;
+using namespace enigma2::utilities;
+
+#define FAST_RECONNECT_ATTEMPTS     (5)
+#define FAST_RECONNECT_INTERVAL   (500) // ms
+#define SLOW_RECONNECT_INTERVAL  (5000) // ms
+
+/*
+ * HTSP Connection handler
+ */
```
Comment (ksooo) [inline src/enigma2/ConnectionManager.cpp]: HTSP? Nope? This is tvheadend comm protocol...

File: src/enigma2/ConnectionManager.cpp [hunk 7]
```diff
@@ -0,0 +1,180 @@
...
+    if (newState == PVR_CONNECTION_STATE_SERVER_UNREACHABLE)
+    {
+      m_connectionListener.ConnectionLost();
+    }
+    else if (newState == PVR_CONNECTION_STATE_CONNECTED)
+    {
+      m_connectionListener.ConnectionEstablished();
+    }
+
+    /* Notify connection state change (callback!) */
```
Comment (ksooo) [inline src/enigma2/ConnectionManager.cpp]: I see "my" code here... Seems, I coded something useful...

File: pvr.vuplus/resources/settings.xml [hunk 8]
```diff
@@ -146,6 +146,39 @@
...
           <control type="list" format="integer" />
         </setting>
+        <setting id="channelandgroupupdatemode" type="integer" label="30116">
+          <level>0</level>
+          <default>0</default>
+          <constraints>
+            <options>
+              <option label="30117">0</option> <!-- DISABLED -->
+              <option label="30118">1</option> <!-- NOTIFY_AND_LOG -->
+              <!--<option label="30119">2</option>--> <!-- RELOAD_CHANNELS_AND_GROUPS -->
```
[the remark this answers is not in the document]
Comment (phunkyfish) [reply pvr.vuplus/resources/settings.xml]: Was just getting this ready for when I enable automatic reloading of channels. Right now it will just notify. Plan to enable that option in the next PR.

File: src/enigma2/data/Channel.cpp [hunk 9]
```diff
@@ -14,6 +14,35 @@ using namespace enigma2;
 using namespace enigma2::data;
 using namespace enigma2::utilities;
 
+bool Channel::Like(const Channel &right) const
+{
+  bool isLike = true;
+  isLike = isLike && (m_serviceReference == right.m_serviceReference);
+  isLike = isLike && (m_channelName == right.m_channelName);
```
[the remark this answers is not in the document]
Comment (phunkyfish) [reply src/enigma2/data/Channel.cpp]: I actually had tried &&= but it doesn't exist. Didn't think that &= would do the same thing in case of bool. Which makes sense why &&= isn't there.

File: src/enigma2/ConnectionManager.cpp (hunk 6 above)
Comment (phunkyfish) [reply src/enigma2/ConnectionManager.cpp]: Done

File: src/enigma2/ConnectionManager.cpp (hunk 5 above)
Comment (phunkyfish) [reply src/enigma2/ConnectionManager.cpp]: Done, and thank you hts ;)

File: src/enigma2/ConnectionManager.cpp (hunk 7 above)
Comment (phunkyfish) [reply src/enigma2/ConnectionManager.cpp]: Don't you always ;)

File: src/Enigma2.cpp (hunk 4 above)
Comment (phunkyfish) [reply src/Enigma2.cpp]: Done

File: src/enigma2/data/ChannelGroup.cpp (hunk 3 above)
Comment (phunkyfish) [reply src/enigma2/data/ChannelGroup.cpp]: But then how would I pull the channels from two different vectors? If I had one vector that would make sense. Or I'm missing something?

Comment (ksooo) [reply src/enigma2/data/ChannelGroup.cpp]: Ah, I see. Overlooked m_chanellist vs. right.m_channellist. nvm.

File: pvr.vuplus/resources/settings.xml (hunk 8 above)
[the remark this answers is not in the document]
Comment (ksooo) [reply pvr.vuplus/resources/settings.xml]: k

File: src/enigma2/data/AutoTimer.cpp [hunk 10]
```diff
@@ -90,6 +90,10 @@ bool AutoTimer::UpdateFrom(TiXmlElement* autoTimerNode, Channels &channels)
   //this is an auto timer so the state is always scheduled unless it's disabled
   m_state = PVR_TIMER_STATE_SCHEDULED;
 
+  m_tags = "";
```
[the remark this answers is not in the document]
Comment (phunkyfish) [reply src/enigma2/data/AutoTimer.cpp]: Done

File: src/Enigma2.h [hunk 11]
```diff
@@ -90,7 +90,7 @@ class Enigma2  : public P8PLATFORM::CThread
   PVR_ERROR GetTunerSignal(PVR_SIGNAL_STATUS &signalStatus);
 
 protected:
-  virtual void *Process(void);
+  virtual void* Process() override;
```
[the remark this answers is not in the document]
Comment (phunkyfish) [reply src/Enigma2.h]: Done

File: src/enigma2/data/Channel.cpp [hunk 12]
```diff
@@ -14,6 +14,35 @@ using namespace enigma2;
 using namespace enigma2::data;
 using namespace enigma2::utilities;
 
+bool Channel::Like(const Channel &right) const
+{
+  bool isLike = true;
+  isLike = isLike && (m_serviceReference == right.m_serviceReference);
```
[the remark this answers is not in the document]
Comment (phunkyfish) [reply src/enigma2/data/Channel.cpp]: Done

File: src/enigma2/data/Channel.cpp (hunk 9 above)
[the remark this answers is not in the document]
Comment (phunkyfish) [reply src/enigma2/data/Channel.cpp]: Done

File: src/enigma2/Channels.cpp [hunk 13]
```diff
@@ -241,4 +243,54 @@ bool Channels::LoadChannels(const std::string groupServiceReference, const std::
...
+
+ChannelsChangeState Channels::CheckForChannelAndGroupChanges(enigma2::ChannelGroups &latestChannelGroups, enigma2::Channels &latestChannels)
+{
+  if (GetNumChannels() != latestChannels.GetNumChannels())
+    return ChannelsChangeState::CHANNELS_CHANGED;
+
+  int foundCount = 0;
+  for (const auto& channel : m_channels)
+  {
+    std::shared_ptr<Channel> channelPtr = latestChannels.GetChannel(channel->GetServiceReference());
```
[the remark this answers is not in the document]
Comment (phunkyfish) [reply src/enigma2/Channels.cpp]: Done

File: src/enigma2/data/EpgPartialEntry.h [hunk 14]
```diff
@@ -2,17 +2,22 @@
...
+    class EpgPartialEntry : public BaseEntry
     {
-      std::string title;
-      std::string shortDescription;
-      unsigned int epgUid;
+      public:
+        unsigned int GetEpgUid() const { return m_epgUid; }
+        void SetEpgUid(unsigned int value) { m_epgUid = value; }
+
+        bool EntryFound() { return m_epgUid != 0; };
```
[the remark this answers is not in the document]
Comment (phunkyfish) [reply src/enigma2/data/EpgPartialEntry.h]: Done

**Comment by phunkyfish** [comment]
Will push the review changes once I get home. Just need to give a test run using the actual build so we don't have a repeat of the last PR ;)

**Comment by phunkyfish** [comment]
Had to add an extra commit to deal with plot vs plotOutline for timers. 

Ready to go!

**Comment by phunkyfish** [comment]
Changing last commit

**Comment by phunkyfish** [comment]
Ok, it's really ready now ;)
