### PR TITLE
Load config if enabled

### LINKED ISSUE #136: Only load Season info extractor and genre mappers config when enabled

### LINKED ISSUE #139: 3.15.1 dont load/work on old DM800se
On my old DM800se the "e2distroversion" string dont exist in webinterface:

```
<e2deviceinfo>
<e2enigmaversion>2016-06-16-tarball</e2enigmaversion>
<e2imageversion>imagename 2016-10-23</e2imageversion>
<e2webifversion>1.7.5</e2webifversion>
<e2fpversion>3</e2fpversion>
```

Kodi.log output:
```
13:09:26.978 T:153837618416  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - Open - VU+ Addon Configuration options
13:09:26.978 T:153837618416  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - Open - Hostname: '192.168.1.60'
13:09:26.978 T:153837618416  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - Open - WebPort: '80'
13:09:26.978 T:153837618416  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - Open - StreamPort: '8001'
13:09:26.978 T:153837618416  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - Open Use HTTPS: 'false'
13:09:27.553 T:153837618416  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - LoadDeviceInfo - DeviceInfo
13:09:27.554 T:153837618416  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - LoadDeviceInfo - E2EnigmaVersion: 2016-06-16-tarball
13:09:27.554 T:153837618416  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - LoadDeviceInfo - E2ImageVersion: imagename 2016-10-23
13:09:27.554 T:153837618416   ERROR: AddOnLog: Enigma2 Client: pvr.vuplus - LoadDeviceInfo Could not parse e2distroversion from result!
13:09:27.554 T:153837618416   ERROR: AddOnLog: Enigma2 Client: pvr.vuplus - Open It seem's that the webinterface cannot be reached. Make sure that you set the correct configuration options in the addon settings!
13:09:27.555 T:153837618416   ERROR: ADDON: Dll Enigma2 Client - Client returned bad status (1) from Create and is not usable
```

The old 3.14 version works.

### LINKED ISSUE #140: Missing default value from timeshift buffer path

### LINKED ISSUE #141: Channel Group Member Order not preserved
With 3.15.1 channels order is not same with backend.

### PR DESCRIPTION
**Pull request by phunkyfish**
v3.15.2
- Fixed: Only load Season info extractor and genre mappers config when enabled, fixes #136 
- Fixed: 3.15.1 dont load/work on old DM800se, fixes #139
- Fixed: Missing default value from timeshift buffer path, fixes #140
- Fixed: Channel Group Member Order not preserved, fixes #141

### CODE REVIEW

**Comment by phunkyfish** [comment]
@ksooo ready for reivew now. Just some small fixes.

**Comment by phunkyfish** [comment]
Actually, one other fix for channel group ordering.

**Comment by phunkyfish** [comment]
@ksooo would be great if have a little bit of time to review this. I've added some debug logging to help with diagnosing what's going on with #145. Once that's in I can create a bug report for Libreeelec.

**Comment by kid63** [comment]
Hello @phunkyfish and @ksooo,
yeah, would be great because of the dreambox-fix, none of the Dreamboxes has got a distroversion implemented. Got a dm920 and 3.15.1 doesn't work at all for Dreambox-Users, not just the old ones. As a workaround i tared the 3.14 and extract it back, but it's unsatisfying. 

Regards 
kid

**Comment by MilhouseVH** [comment]
@phunkyfish I'll include this PR in the next LibreELEC nightly (Saturday night, `#1201`), hopefully we can get you the information you need.

**Comment by phunkyfish** [comment]
Thanks @MilhouseVH

**Comment by phunkyfish** [comment]
@MilhouseVH thanks again for including. This did indeed help me find the issue.

There was a new option added at some point to PVR settings "Synchronise channel groups with backend(s)". It would appear that in stock kodi this gets enabled by default, whereas in libreelec it does not or something to that effect.

**Comment by phunkyfish** [comment]
@ksooo this PR has been soak tested for several days now so should be ok to put through.

**Comment by MilhouseVH** [comment]
@phunkyfish ah yes, LibreELEC disables that option in `appliance.xml`, [here](https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/mediacenter/kodi/config/appliance.xml#L70-L76). Not entirely sure why it is disabled, but it's something that has been disabled for a 3 years (original commit back in [OpenELEC days](https://github.com/LibreELEC/LibreELEC.tv/commit/4d23f2d4970fa18fdd233c568efe52e04527d90d). I'll ask around and see if anyone from the LE team remembers.

**Comment by MilhouseVH** [comment]
So far nobody knows why it was disabled (although it's late on Sunday night... :))

For now I'll [revert](https://github.com/LibreELEC/LibreELEC.tv/commit/6a754a4eec80727f681b0daa8e17d7fe0db333c1) the LibreELEC commit in nightly test builds so that `pvrmanager.syncchannelgroups` is enabled as it is in stock Kodi, and we can gauge the effect.

**Comment by kid63** [comment]
Hi,

unfortunately #137  ignores the Favourite-Bouqets from Dreamboxes, only freetv is displayed. Was working in 3.14, that's the latest version it worked, because 3.15.1 wasn't for Dreamboxes. Tested it with OSMC.

cu

**Comment by phunkyfish** [comment]
In this version on the channels tab you need to select the favourites (as first or last group) in addition to All Bouquets.

It was the only way I could get it work across all hardware and images.  Not all images process favourites in the same way.

As I don’t have a dream box I didn’t test that specific hardware.

**Comment by kid63** [comment]
Thanks for pointing me in the right direction, will have a look. :)

**Comment by Matthias1992** [comment]
Hey guys,
I still have the same problem with,
Kodi (18.0-RC3 Git:20181210-c6107e5). Platform: Linux x86 64-bit
and an DM800SE

Enigma2 Client: pvr.vuplus - LoadDeviceInfo Could not parse e2distroversion from result!

But I don't get @phunkyfish what do you mean to fix is with the Bouquets.
A longer explain would be nice, 
just a kodi noob :)
Matthias

**Comment by phunkyfish** [comment]
This PR covers a number of the bug fixes. The bouquets stuff is not related to the fix for e2distroversion

File: src/Enigma2.cpp [hunk 1]
```diff
@@ -299,11 +299,10 @@ bool Enigma2::OpenLiveStream(const PVR_CHANNEL &channelinfo)
       // Zapping is set to true, so send the zapping command to the PVR box
       std::string strServiceReference = m_channels.GetChannel(channelinfo.iUniqueId)->GetServiceReference().c_str();
 
-      std::string strTmp;
-      strTmp = StringUtils::Format("web/zap?sRef=%s", WebUtils::URLEncodeInline(strServiceReference).c_str());
+      std::string strCmd = StringUtils::Format("web/zap?sRef=%s", WebUtils::URLEncodeInline(strServiceReference).c_str());
```
Comment (ksooo) [inline src/Enigma2.cpp]: `const std::string`?

File: src/enigma2/Channels.cpp [hunk 2]
```diff
@@ -153,8 +153,7 @@ bool Channels::LoadChannels(const std::string groupServiceReference, const std::
 {
   Logger::Log(LEVEL_INFO, "%s loading channel group: '%s'", __FUNCTION__, groupName.c_str());
 
-  std::string strTmp;
-  strTmp = StringUtils::Format("%sweb/getservices?sRef=%s", Settings::GetInstance().GetConnectionURL().c_str(), WebUtils::URLEncodeInline(groupServiceReference).c_str());
+  std::string strTmp = StringUtils::Format("%sweb/getservices?sRef=%s", Settings::GetInstance().GetConnectionURL().c_str(), WebUtils::URLEncodeInline(groupServiceReference).c_str());
```
Comment (ksooo) [inline src/enigma2/Channels.cpp]: `const std::string`?

File: src/Enigma2.cpp (hunk 1 above)
Comment (phunkyfish) [reply src/Enigma2.cpp]: I'll go through the go base and clean this up in general. Been meaning to do it for a while.

File: src/enigma2/Channels.cpp (hunk 2 above)
Comment (phunkyfish) [reply src/enigma2/Channels.cpp]: I'll go through the go base and clean this up in general. Been meaning to do it for a while. Will include in next PR

**Comment by phunkyfish** [comment]
@MilhouseVH thanks for including in nightlies, it should come via master now.
